version: "3"
services: 
  airgab:
    image: wiedmannfelix/airgab
    container_name: airgab
    command: --user=pi \
              --host=192.168.2.233 \
              --source=/opt/ghost \
              --destination=/home/pilot/backup/ \
              --options=-a \
              --interval=10s \
              --private-key=$HOME/.ssh/id_rsa
    ports: 
      - "9100:9100"
    volumes: 
      - "$PWD/backup:/home/pilot/backup"
      - "$HOME/.ssh/id_rsa:/home/pilot/.id_rsa"